backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "index"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "index-page"
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Blok 1"
            name: "homeBlock1"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "text"
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Link"
                name: "link"
                widget: "object"
                fields:
                  - label: "Text"
                    name: "text"
                    widget: "text"
                  - label: "Url"
                    name: "url"
                    widget: "string"
          - label: "Blok 2"
            name: "homeBlock2"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "text"
              - label: "Tools"
                name: "tools"
                widget: "list"
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "image"
                    required: "false"
                  - label: "Title"
                    name: "title"
                    widget: "string"
                    required: "false"
                  - label: "Text"
                    name: "text"
                    widget: "text"
                    required: "false"
          - label: "Logos"
            name: "customerDisplay"
            widget: "object"
            fields:
              - label: "Titel"
                name: "title"
                widget: "string"
              - label: "Logos"
                name: "logos"
                widget: "list"
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "image"
                  - label: "Link"
                    name: "url"
                    widget: "string"
          - label: "Blok 3"
            name: "homeBlock3"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Achtergrond afbeelding"
                name: "backgroundImage"
                widget: "image"
              - label: "Blokken"
                name: "blocks"
                widget: "list"
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "image"
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Text"
                    name: "text"
                    widget: "text"
                  - label: "Link"
                    name: "link"
                    widget: "string"
                  - label: "Alleen afbeelding weergeven"
                    name: "imageOnly"
                    widget: "boolean"
      - file: "src/pages/diensten/index.md"
        label: "Diensten"
        name: "diensten"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services-page"}
          - {label: "Title", name: "title", widget: "string"}
          - label: "Intro"
            name: "intro"
            widget: "list"
          - label: "Pricing"
            name: "pricing"
            widget: "object"
            fields:
              - label: "Options"
                name: "options"
                widget: "list"
                fields:
                  - label: "Text"
                    name: "text"
                    widget: "string"
                  - label: "Link text"
                    name: "linkText"
                    widget: "string"
                  - label: "Url"
                    name: "url"
                    widget: "string"
          - label: "Fases"
            name: "fases"
            widget: "object"
            fields:
              - label: "Heading"
                name: "heading"
                widget: "string"
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Text"
                    name: "text"
                    widget: "text"
                  - label: "Image"
                    name: "image"
                    widget: "image"
      - file: "src/pages/ons-verhaal/index.md"
        label: "Ons verhaal"
        name: "ons-verhaal"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - label: "Intro"
            name: "intro"
            widget: "list"
          - label: "Fases"
            name: "fases"
            widget: "object"
            fields:
              - label: "Heading"
                name: "heading"
                widget: "string"
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Text"
                    name: "text"
                    widget: "text"
                  - label: "Image"
                    name: "image"
                    widget: "image"
      - file: "src/pages/about/index.md"
        label: "Over ons"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

