backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "index"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "index-page"
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Blok 1"
            name: "homeBlock1"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "text"
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Link"
                name: "link"
                widget: "object"
                fields:
                  - label: "Text"
                    name: "text"
                    widget: "text"
                  - label: "Url"
                    name: "url"
                    widget: "string"
          - label: "Blok 2"
            name: "homeBlock2"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "text"
              - label: "Tools"
                name: "tools"
                widget: "list"
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "image"
                    required: "false"
                  - label: "Title"
                    name: "title"
                    widget: "string"
                    required: "false"
                  - label: "Text"
                    name: "text"
                    widget: "text"
                    required: "false"
          - label: "Blok 3"
            name: "homeBlock3"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Achtergrond afbeelding"
                name: "backgroundImage"
                widget: "image"
              - label: "Blokken"
                name: "blocks"
                widget: "list"
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "image"
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Text"
                    name: "text"
                    widget: "text"
                  - label: "Link"
                    name: "link"
                    widget: "string"
      - file: "src/pages/diensten/index.md"
        label: "Diensten"
        name: "diensten"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services-page"}
          - {label: "Title", name: "title", widget: "string"}
          - label: "Intro"
            name: "intro"
            widget: "list"
          - label: "Sub title"
            name: "subTitle"
            widget: "string"
          - label: "Intro"
            name: "intro"
            widget: "string"
          - label: "Banner"
            name: "bannerImage"
            widget: "image"
          - label: "Ideëen brouwerij"
            name: "ideeenBrouwerij"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "image"
                name: "image"
                widget: "image"
              - label: "lead"
                name: "lead"
                widget: "text"
              - label: "intro"
                name: "intro"
                widget: "text"
              - label: "Blokken"
                name: "items"
                widget: "list"
                fields:
                  - label: "Titel"
                    name: "title"
                    widget: "string"
                  - label: "Tekst"
                    name: "text"
                    widget: "text"
                  - label: "Afbeelding"
                    name: "image"
                    widget: "image"
              - label: "Call to action"
                name: "cta"
                widget: "object"
                fields:
                  - label: "Tekst"
                    name: "question"
                    widget: "string"
                  - label: "Link tekst"
                    name: "linkText"
                    widget: "string"
                  - label: "Url"
                    name: "linkUrl"
                    widget: "string"
          - label: "Verander aanjagers"
            name: "veranderAanjagers"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "image"
                name: "image"
                widget: "image"
              - label: "Blokken"
                name: "items"
                widget: "list"
                fields:
                  - label: "Titel"
                    name: "title"
                    widget: "string"
                  - label: "Tekst"
                    name: "text"
                    widget: "text"
                  - label: "Afbeelding"
                    name: "image"
                    widget: "image"
          - label: "Dienst aankondiging"
            name: "dienstAnnouncement"
            widget: "object"
            fields:
              - label: "Titel"
                name: "title"
                widget: "string"
              - label: "Onder titel"
                name: "subTitle"
                widget: "string"
              - label: "Tekst"
                name: "announcement"
                widget: "text"
              - label: "Afsluiter"
                name: "finish"
                widget: "string"

      - file: "src/pages/ons-verhaal/index.md"
        label: "Ons verhaal"
        name: "ons-verhaal"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - label: "Blok 1"
            name: "aboutBlock1"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "Intro"
                name: "intro"
                widget: "list"
              - label: "Banner"
                name: "background"
                widget: "image"
          - label: "Blok 2"
            name: "aboutBlock2"
            widget: "object"
            fields:
              - label: "Titel"
                name: "title"
                widget: "string"
              - label: "Het team"
                name: "persons"
                widget: "list"
                fields:
                  - label: "Naam"
                    name: "title"
                    widget: "string"
                  - label: "Toon popup"
                    name: "featured"
                    widget: "boolean"
                  - label: "Vragen"
                    name: "list"
                    widget: "list"
                    fields:
                      - label: "Vraag"
                        name: "question"
                        widget: "string"
                      - label: "Antwoord"
                        name: "answer"
                        widget: "string"
                  - label: "Functie"
                    name: "position"
                    widget: "string"
                  - label: "Profiel foto"
                    name: "image"
                    widget: "widget"
                  - label: "LinkedIn link"
                    name: "linkedIn"
                    widget: "string"
                  - label: "E-mail"
                    name: "mail"
                    widget: "string"
              - label: "Afsluiter"
                name: "extraBlock"
                widget: "object"
                fields:
                  - label: "Titel"
                    name: "title"
                    widget: "string"
                  - label: "Onder titel"
                    name: "subTitle"
                    widget: "string"
                  - label: "Afbeelding"
                    name: "image"
                    widget: "image"


  - name: "blog"
    label: "Blog"
    folder: "src/pages/short-stories"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

