backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "index"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "index-page"
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Blok 1"
            name: "homeBlock1"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "text"
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Link"
                name: "link"
                widget: "object"
                fields:
                  - label: "Text"
                    name: "text"
                    widget: "text"
                  - label: "Url"
                    name: "url"
                    widget: "string"
          - label: "Blok 2"
            name: "homeBlock2"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "text"
              - label: "Tools"
                name: "tools"
                widget: "list"
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "image"
                    required: "false"
                  - label: "Title"
                    name: "title"
                    widget: "string"
                    required: "false"
                  - label: "Text"
                    name: "text"
                    widget: "text"
                    required: "false"
          - label: "Logos"
            name: "customerDisplay"
            widget: "object"
            fields:
              - label: "Titel"
                name: "title"
                widget: "string"
              - label: "Logos"
                name: "logos"
                widget: "list"
                fields:
                  - label: "Naam"
                    name: "name"
                    widget: "string"
                  - label: "Beschrijving"
                    name: "description"
                    widget: "string"
                  - label: "Image"
                    name: "image"
                    widget: "image"
                  - label: "Link"
                    name: "url"
                    widget: "string"
          - label: "Blok 3"
            name: "homeBlock3"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Achtergrond afbeelding"
                name: "backgroundImage"
                widget: "image"
              - label: "Blokken"
                name: "blocks"
                widget: "list"
                fields:
                  - label: "Image"
                    name: "image"
                    widget: "image"
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Text"
                    name: "text"
                    widget: "text"
                  - label: "Link"
                    name: "link"
                    widget: "string"
                  - label: "Alleen afbeelding weergeven"
                    name: "imageOnly"
                    widget: "boolean"
      - file: "src/pages/diensten/index.md"
        label: "Diensten"
        name: "diensten"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services-page"}
          - {label: "Title", name: "title", widget: "string"}
          - label: "Banner afbeelding"
            name: "bannerImage"
            widget: "image"
          - label: "Secties"
            name: "services"
            widget: "list"
            fields:
              - label: "Titel"
                name: "title"
                widget: "string"
              - label: "Content"
                name: "content"
                widget: "object"
                fields:
                  - label: "Titel"
                    name: "title"
                    widget: "string"
                  - label: "Korte tekst"
                    name: "text"
                    widget: "string"
              - label: "Lange tekst"
                name: "extraContent"
                widget: "markdown"
              - label: "Afbeelding 1"
                name: "image1"
                widget: "image"
              - label: "Afbeelding 2"
                name: "image2"
                widget: "image"
              - label: "Afbeelding 3"
                name: "image3"
                widget: "image"
              - label: "Afbeelding 4"
                name: "image4"
                widget: "image"
              - label: "Afbeelding 5"
                name: "image5"
                widget: "image"
              - label: "Quote"
                name: "quote"
                widget: "object"
                fields:
                  - label: "Tekst"
                    name: "text"
                    widget: "string"
                  - label: "Auteur"
                    name: "author"
                    widget: "string"
      - file: "src/pages/ons-verhaal/index.md"
        label: "Ons verhaal"
        name: "ons-verhaal"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - label: "Blok 1"
            name: "aboutBlock1"
            widget: "object"
            fields:
              - label: "Titel"
                name: "title"
                widget: "string"
              - label: "Intro"
                name: "intro"
                widget: "text"
              - label: "Achtergrond afbeelding"
                name: "background"
                widget: "image"
          - label: "Blok 2"
            name: "aboutBlock2"
            widget: "object"
            fields:
              - label: "Titel"
                name: "title"
                widget: "string"
              - label: "Personen"
                name: "persons"
                widget: "list"
                fields:
                  - label: "Naam"
                    name: "title"
                    widget: "string"
                  - label: "Meer weergeven"
                    name: "featured"
                    widget: "boolean"
                    default: false
                  - label: "Weetjes"
                    name: "list"
                    widget: "list"
                    fields:
                      - label: "Vraag"
                        name: "question"
                        widget: "string"
                      - label: "Antwoord"
                        name: "answer"
                        widget: "string"
                  - label: "Functie"
                    name: "position"
                    widget: "string"
                  - label: "Profielfoto"
                    name: "image"
                    widget: "image"
                  - label: "LinkedIn"
                    name: "linkedIn"
                    widget: "string"
                  - label: "Email"
                    name: "mail"
                    widget: "string"
  - name: "blog"
    label: "Short stories"
    folder: "src/pages/short-stories"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", default: ['Story']}

